apiVersion: v1
kind: Secret
metadata:
  name: cloudinit-secret
stringData:
  userdata: |-
              #cloud-config
              users:
              - name: ubuntu
                ssh_authorized_keys:
                - ssh-rsa AAAAB3NzaC1yc2E ... ## supply your key here
                sudo: ALL=(ALL) NOPASSWD:ALL
                lock_passwd: false
                plain_text_passwd: 'ubuntu'
                shell: /bin/bash