apiVersion: v1
kind: Secret
metadata:
  name: cloudinit-secret
stringData:
  userdata: |-
              #cloud-config
              users:
              - name: ubuntu
                ssh_authorized_keys:
                - ssh-rsa AAAAB3NzaC1yc2E ... ## supply your key here
                sudo: ALL=(ALL) NOPASSWD:ALL
                lock_passwd: false
                plain_text_passwd: 'ubuntu'
                shell: /bin/bash
  networkData: |-
    network:
      version: 2
      ethernets:
        enp1s0:
          dhcp4: true
      
# The networkData section is needed only for Ubuntu VMs. 
# In KubeVirt, the MAC address changes after a VM restart. Ubuntu retains this MAC address in its network settings, so after rebooting, these MAC addresses won't match the previous ones. 

# To overcome this behaviour of Ubuntu it is recommended to use cloud-init which would initiate a DHCP call. More details here, https://github.com/kubevirt/kubevirt/issues/1646#issuecomment-433262034
