apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: demo-vm-from-image-url
  labels:
    vm: demo-vm-from-image-url # service are expose based on this label
spec:
  # Define the instance type and preference
  # You can find all the instance types here, https://github.com/kubevirt/common-instancetypes?tab=readme-ov-file#resources
  instancetype:
    kind: VirtualMachineClusterInstancetype
    name: u1.medium  # run 'kubectl get vmcfs' to see all the available instancetypes
  preference:
    kind: VirtualMachineClusterPreference
    name: ubuntu # change this based on the image, avaialble options can be found in `kubectl get vmcps`
  
  # Set the VM to always run
  runStrategy: Always
  
  # VM template specification
  template:
    metadata:
      labels:
        vm: demo-vm-from-image-url # service are expose based on this label
    spec:
      domain:
        devices:
          # Define disks
          disks:
          - disk:
              bus: virtio
            name: disk1
          - disk:
              bus: virtio
            name: cloudinitdisk
          # Define network interface, https://kubevirt.io/user-guide/network/interfaces_and_networks/
          interfaces:
          - masquerade: {} # In masquerade mode, KubeVirt allocates internal IP addresses to VM and hides them behind NAT
            name: default
      # Define network
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 0
      # Define volumes
      volumes:
      - name: disk1
        dataVolume:
          name: demo-vm-from-image-url
      - name: cloudinitdisk
        cloudInitNoCloud:
          secretRef: 
            name: cloudinit-secret
  # Define data volume template
  dataVolumeTemplates:
  - metadata:
      name: demo-vm-from-image-url
    spec:
      pvc:
        storageClassName: ceph-block
        volumeMode: Block
        accessModes:
        - ReadWriteMany # allow the PVC to be accessed through multiple pods, this is needed for live migration support
        resources:
          requests:
            storage: 10Gi  # this is going to be your VM storage disk size
      source:
        http:
          # Qcow2 is the virtual hard disk format of KVM virtual machine
          # URL for the image source should be specified here
          url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
          ## https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img ## this is 22.04 image
          ## 24.04 https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
          ## 24.10 https://cloud-images.ubuntu.com/oracular/current/oracular-server-cloudimg-amd64.img
          