apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: demo-vm-from-vcenter
spec:
  instancetype:
    kind: VirtualMachineClusterInstancetype
    name: u1.large
  preference:
    kind: VirtualMachineClusterPreference
    name: ubuntu
  runStrategy: Always
  template:
    metadata:
      creationTimestamp: null
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: disk1
          interfaces:
          - masquerade: {}
            name: default
        machine:
          type: ""
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - name: disk1
        dataVolume:
          name: demo-vm-from-vcenter
  dataVolumeTemplates:
  - metadata:
      name: demo-vm-from-vcenter
    spec:
      pvc:
        storageClassName: ceph-block
        volumeMode: Block
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 200Gi
      source:
        vddk:
          backingFile: "[MY_DC-01] VMs/test_jumpbox.vmdk" ## file path to the VMs virtual hard disk
          url: "https://10.12.25.5" ## vCenter URL
          uuid: "4222f3ba-52bb-.."  ## UUID of the VM                 
          thumbprint: "D7:5A:0B:41:B..."  ## certificate thumbprint of the vCenter
          # initImageURL: quay.io/kubevirt/vddk-init:v1.59.0 ## this image is not working and we build a custom init image
          # following https://docs.openshift.com/container-platform/4.8/virt/virtual_machines/importing_vms/virt-importing-vmware-vm.html#virt-creating-vddk-image_virt-importing-vmware-vm
          initImageURL: "quay.io/kubevirt/vddk-init:latest"
          secretRef: "vddk-cred"
