apiVersion: pool.kubevirt.io/v1alpha1
kind: VirtualMachinePool
metadata:
  name: vmpool-nginx-hypervisor
spec:
  replicas: 50
  selector:
    matchLabels:
      app: vmpool-nginx-hypervisor
  virtualMachineTemplate:
    metadata:
      labels:
        app: vmpool-nginx-hypervisor
    spec:
      instancetype:
        kind: VirtualMachineClusterInstancetype
        name: u1.medium
      preference:
        kind: VirtualMachineClusterPreference
        name: ubuntu
      runStrategy: Always
      template:
        metadata:
          labels:
            app: vmpool-nginx-hypervisor
        spec:
          affinity:
            podAntiAffinity: ## set the anti-affinity rule to spread the pods across nodes
              preferredDuringSchedulingIgnoredDuringExecution: ## pods will be scheduled on the same node only if replicas > nodes
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - vmpool-nginx-hypervisor
                  topologyKey: kubernetes.io/hostname   
          domain:
            devices:
              disks:
              - disk:
                  bus: virtio
                name: disk1
              - disk:
                  bus: virtio
                name: cloudinitdisk
              interfaces:
              - masquerade: {}
                name: default
            machine:
              type: ""
          networks:
          - name: default
            pod: {}
          terminationGracePeriodSeconds: 0
          volumes:
          - name: "serviceaccount"
            serviceAccount:
              serviceAccountName: cdi-cloner ## This service account has permissions to clone PVCs from golden-image namespace , it will be exisiting in your namspace.
          - name: disk1
            dataVolume:
              name: vmpool-nginx-hypervisor
          - name: cloudinitdisk
            cloudInitNoCloud:
              secretRef: 
                name: cloudinit-with-nginx-secret
      dataVolumeTemplates:
      - metadata:
          name: vmpool-nginx-hypervisor
        spec:
          pvc:
            storageClassName: ceph-block
            volumeMode: Block
            accessModes:
            - ReadWriteMany
            resources:
              requests:
                storage: 5Gi
          source:
            pvc:
              name: jammy-server-cloudimg-amd64.img
              namespace: golden-images